### ISSUE TITLE
different linux version

### ISSUE THREAD

**Issue by fadi123go** [suurjaak/SQLitely#2]
Can you create a .deb package or appimage ? Pip install does not work on my computer.

**Comment by suurjaak** [comment]
There is a Snap release if that works for you.

**Comment by fadi123go** [comment]
No , I would love to see either deb , rpm or appimage .

**Comment by fadi123go** [comment]
Snap actually works , but I would love to see deb, rpm or appimage , since they load a little faster. Great app by the way and I hope you do not abandon it in the future .

**Comment by suurjaak** [comment]
Thanks! And glad to hear that the snap works. 

Out of curiosity, what distro are you using where both rpms and debs would work? 

Regarding deb/rpm/AppImage releases, AppImage looks like the most doable since it is self-contained whereas all .deb dependencies need to available as .debs as well. But I am quite unfamiliar on how to package a Python application as AppImage.

**Comment by fadi123go** [comment]
I used mageia untill recently, now I use mx linux. I mentioned rpm because some other people may use it, not me . Appimage is the best option, I think. Take your time and learn how to package in it. Good luck.
